import type { NextPage } from "next";
import Head from "next/head";

import Canvas from "../components/Canvas";
import Header from "../components/Header";
import { useEffect, useState } from "react";
import { CANVAS_SIZES } from "../utils";
import { injected } from "../config/wallets";
import { useWeb3React } from "@web3-react/core";

const Home: NextPage = () => {
  const [activeTab, setactiveTab] = useState(1);
  const { account, activate, chainId, deactivate } = useWeb3React();

  useEffect(() => {
    // @ts-ignore TYPE NEEDS FIXING
    if (window?.ethereum) {
      activate(injected);
    } else {
      alert("You need to install a crypto wallet to run this Dapp!!");
    }
  }, [activate]);
  return (
    <div className="">
      <Head>
        <title>NFTs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <div className="container mx-auto my-5 tabs tabs-boxed">
          <button
            className={`tab ${activeTab == 1 ? "tab-active" : ""}`}
            onClick={() => setactiveTab(1)}
          >
            No Color Art
          </button>
          <button
            className={`tab ${activeTab == 2 ? "tab-active" : ""}`}
            onClick={() => setactiveTab(2)}
          >
            Grayscale Art{" "}
          </button>
          <button
            className={`tab ${activeTab == 3 ? "tab-active" : ""}`}
            onClick={() => setactiveTab(3)}
          >
            Color Art
          </button>
        </div>

        <div className="container h-screen mx-auto">
          <Canvas
            size={CANVAS_SIZES[activeTab - 1]}
            typeIndex={activeTab - 1}
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
